### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by elenahnchrk** [elenahnchrk/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by olenalozinska** [comment]
I'm a haute couture model. Creativity is my passion. I’m really interested in theatre. I’m pretty open to a lot of things, which makes me enjoy fashion and making new experiences within it. My approach to life has proved favourable amongst clients in the fashion world. Brands like Maison Margiela and Louis Vuitton constantly include me in projects. I'm represented by Viva Model Management.
