### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by elenahnchrk** [elenahnchrk/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by olenalozinska** [comment]
Personal Contact Information
Instagram https://www.instagram.com/leondame/

Agency Contact Information
Instagram https://www.instagram.com/vivamodel/

Website viva-paris.com

Address 23 Charlotte Road, 3rd Floor, London, EC2A 3PB United Kingdom

https://www.google.com/maps/place/23+Charlotte+Rd,+London+EC2A+3PB,+%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B1%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%96%D1%8F/@51.5256295,-0.0835302,17z/data=!3m1!4b1!4m5!3m4!1s0x48761cbaa7a39e05:0xff6ca4dd77a7e8a5!8m2!3d51.5256295!4d-0.0813415

Phone +44 203 487 1240

Open-call times: 11am-12pm Monday-Friday
