### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by elenahnchrk** [elenahnchrk/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by olenalozinska** [comment]
1998
Was born in Berlin, Germany.

2015
Begun studying Theatre Theory and Politics at the Freie Universität in Berlin.

The same year was scouted while waiting for a bus, and signed the contract with the German agency Tomorrow Is Another Day. The next 5 years allow building up my modelling proficiency and become reputable within the world of fashion.

Also in 2015, participated in the first runway show for Sacai.

2019
Came one of the biggest moments. I was personally chosen by John Galliano to close out the Maison Margiela show. After the show became a prominent figure and consistent face in the industry.

Became Breakout Star by The Models.com - Model of the Year Industry Awards as a newcomer to the fashion industry.

2020
Became one of the Top 50 male models.

Worked with:
Acne Studios
Alexander McQueen
Bottega Veneta
Burberry
Christian Dada
Christopher Raeburn
Damir Doma
Ermenegildo Zegna
Fendi
Feng Chen Wang
Fila
Givenchy
GQ Style China
Gucci
Hermès
Hugo Boss
Isabel Marant
John Galliano
Just Cavalli
Kenzo
L'Uomo Vogue
Lacoste
Lanvin
Louis Vuitton
Maison Margiela
Models.com
Roberto Cavalli
Sacai
Tommy Hilfiger
Uniqlo
Valentino
Vogue Hommes
Zara
