### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by elenahnchrk** [elenahnchrk/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by olenalozinska** [comment]
Gallery

![244B14D4-451B-42C5-BB5A-34EDFF40A5D6](https://user-images.githubusercontent.com/83592191/117000708-2fd8e380-acea-11eb-809d-8e87c7f58501.jpeg)
![B1B50E11-834D-464A-B218-5ED4D3C45D22](https://user-images.githubusercontent.com/83592191/117000712-310a1080-acea-11eb-8c53-426c3bfd6e13.jpeg)
![EBA5E68C-2A4C-4CF9-9661-F5EA9DEA5547](https://user-images.githubusercontent.com/83592191/117000718-32d3d400-acea-11eb-8e67-409ae77e67be.jpeg)
![CAAD833D-7D0E-41CE-A71D-261B647369EB](https://user-images.githubusercontent.com/83592191/117000722-34050100-acea-11eb-9738-8b244dee9b9d.jpeg)
![86688D41-229E-42A3-BD61-2958A532F1CC](https://user-images.githubusercontent.com/83592191/117000723-34050100-acea-11eb-90f1-ee00f5f877d6.jpeg)
![E22FA2A3-9473-4FBA-8A2C-4007907405D7](https://user-images.githubusercontent.com/83592191/117000726-349d9780-acea-11eb-85e7-36058f637223.jpeg)

**Comment by elenahnchrk** [comment]
Runway collection
[https://www.youtube.com/watch?v=By5Pcaw9Uw4](url)
